version: "3"
services: 
 db:
  restart: always
  container_name: mysql
  command: 
   --lower_case_table_names=1
   --character-set-server=utf8mb4
   --collation-server=utf8mb4_general_ci
   --explicit_defaults_for_timestamp=true
   --lower_case_table_names=1
  image: mysql:5.7
  environment:
   TZ: Asia/Shanghai
   MYSQL_ROOT_PASSWORD: root123456
  ports:
   - 63306:3306
  volumes: 
   - ./data:/var/lib/mysql
